config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :jobs do 
    resource :favorites, only: [:create, :destroy]
  end
  
  devise_for :users
  resources :users, only:[:index, :show, :update, :edit]
  resources :shifts
  resources :rooms

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    has_many :favorites

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :attendance
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :favorites, dependent: :destroy 
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 今日出席したかどうかというメソッド
  def today_attendance
    Attendance.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, user_id: id).first
  end
      
end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        jobs_path
    end


    def clock_in?(attendance)
        return false if attendance.nil?
        !attendance.clock_in_at.nil?
    end

    def clock_out?(attendance)
        return false if attendance.nil?
        !attendance.clock_out_at.nil?
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    attendance = Attendance.find(params[:job_id])
    favorite = current_user.favorites.new(attendance_id: attendance.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy 
    attendance = Attendance.find(params[:job_id])
    favorite = current_user.favorites.find_by(attendance_id: attendance.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
        @attendances = Attendance.where(created_at: Time.zone.now.all_day)
        @attendance = current_user.attendances
        last_attendance = current_user.today_attendance
        @is_clocked_in = clock_in?(last_attendance)
        @is_clocked_out = clock_out?(last_attendance)
    end

    def create
        @attendance = current_user.today_attendance
        # 出席したかどうかという情報が入る
        is_clocked_in = clock_in?(@attendance)
        
        # 退席したかどうかという情報が入る
        is_clocked_out = clock_out?(@attendance)
        if !is_clocked_in && !is_clocked_out
            @attendance = current_user.attendances.build(clock_in_at: Time.zone.now)
            flash[:success] = "部活に参加しました。"
        elsif is_clocked_in && !is_clocked_out
            @attendance.clock_out_at = Time.zone.now
            flash[:success] = "部活を終えました。"
        end
        @attendance.save
        redirect_to jobs_path
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @currentEntries = current_user.entries
    #@currentEntriesのルームを配列にする
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    #@currentEntriesのルーム且つcurrent_userでないEntryを新着順で取ってくる
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: @user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    #ルームが作成されているかどうか
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @direct_messages = @room.direct_messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "DM")
    #entryにログインユーザーを作成
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    #entryにparamsユーザーを作成
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end

  def destroy
      room = Room.find(params[:id])
      room.destroy
      redirect_to rooms_path
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.new(shift_params)
    if @shift.save
     redirect_to shifts_path, notice: 'シフトを登録しました。'
    else
      render :new
    end
  end

  def index
    @shifts = Shift.all
  end

  def show
    @shift = Shift.find(params[:id])
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])  
    if @shift.update(shift_params)
      redirect_to shifts_path, notice: 'シフトを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    redirect_to shifts_path
  end

  private
  def shift_params
    params.require(:shift).permit(:start_time, :end_time, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
      @attendances = @user.attendances

      if user_signed_in?
        #Entry内のuser_idがcurrent_userと同じEntry
        @currentUserEntry = Entry.where(user_id: current_user.id)
        #Entry内のuser_idがMYPAGEのparams.idと同じEntry
          @userEntry = Entry.where(user_id: @user.id)
            #@user.idとcurrent_user.idが同じでなければ
            unless @user.id == current_user.id
              @currentUserEntry.each do |cu|
                @userEntry.each do |u|
                  #もしcurrent_user側のルームidと＠user側のルームidが同じであれば存在するルームに飛ぶ
                  if cu.room_id == u.room_id then
                    @isRoom = true
                    @roomId = cu.room_id
                  end
                end
              end
              #ルームが存在していなければルームとエントリーを作成する
              unless @isRoom
                @room = Room.new
                @entry = Entry.new
              end
            end
        end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update(user_params)
      redirect_to user_path(@user.id)
    end

  
    private 
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def weekly_columns
        ['activity_monday', 'activity_tuesday', 'activity_wednesday',\
        'activity_thursday', 'activity_friday', 'activity_saturday']
    end

    def users
        users = []
        User.all.each do |user|
            users.push
        end
    end
end

app/views/homes/top.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>勤怠管理アプリ</h1>
        <p id="RealtimeClockArea2"></p>
        <%= link_to "新規登録" , new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "ログイン" , new_user_session_path, class: "btn  btn-primary" %>
      </div>
    </div>
  </div>

<%#時計表示: 参考文献 %>
<%# https://www.nishishi.com/javascript-tips/realtime-clock-setinterval.html %>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="mb-4">勤怠状況</h3>
      <h3 class="mb-4">本日の勤怠状況</h3>

      <%= form_with model: @attendance , url:'/jobs' ,  local:true do |f| %>
        <% if (!@is_clocked_in && !@is_clocked_out) %>
          <%= f.submit "出勤", class: "btn btn-primary" %>
        <% elsif @is_clocked_in && !@is_clocked_out %>
          <%= f.submit "退勤", class: "btn btn-primary" %>
        <% else %>
          <%= f.submit "退勤済み" ,  class: "btn btn-primary", disabled: true %>
        <% end %>
      <% end %>

      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>名前</th>
            <th>出席時刻</th>
            <th>退席時刻</th>
            <th>いいね数</th>
          </tr>
        </thead>
        <% @attendances.each do |attendance| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(attendance.user.id) do %>
                  <%= attendance.user.name %>
                <% end %>
              </td>
              <td>
                <%= attendance.clock_in_at.strftime('%Y/%m/%d %H:%M:%S')  %>
              </td>
              <td>
                <% if attendance.clock_out_at.present? %>
                  <%= attendance.clock_out_at.strftime('%Y/%m/%d %H:%M:%S') %> 
                <% else %>
                  N/A
                <% end %>
              </td>
              <td>
                <% if attendance.favorited_by?(current_user) %>
                  <%= link_to job_favorites_path(attendance.id), method: :delete do %>
                    <i class="fa fa-heart text-danger" aria-hidden="true"></i>
                    <%= attendance.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to job_favorites_path(attendance.id), method: :post do %>
                    <i class="fa fa-heart text-primary" aria-hidden="true"></i>
                    <%= attendance.favorites.count %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<h2>メッセージ一覧</h2>
<% @anotherEntries.each do |e| %>
  <div class="card my-3">
    <div class="card-body d-flex justify-content-between align-items-center">
      <div>
        <!-- 名前からroomの詳細に飛べるようにリンク化 -->
        <%= link_to room_path(e.room.id), class: "text-decoration-none" do %>
          <h5 class="card-title"><%= e.user.name %></h5>
        <% end %>

        <% if dm = DirectMessage.find_by(id: e.room.direct_message_ids.last) %>
          <!-- 最新メッセージ内容の最初の10文字を表示する -->
          <p class="card-text"><%= truncate(dm.content, length: 10) %></p>
        <% end %>

        <!-- 更新日時を表示 -->
        <small style="color: #C0C0C0;"><%= e.updated_at.strftime("%Y/%m/%d %H:%M") %></small>
      </div>

      <div>
        <!-- ゴミ箱アイコンクリックでroomを消せるようにする -->
        <%= link_to room_path(e.room.id), method: :delete, class: "text-decoration-none" do %>
          <i class="fas fa-trash fa-lg text-secondary"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/show.html.erb
<% @entries.each do |e| %>
  <% current_user.id == e.user_id ? @class = "current_user" : @class = ""  %>
  <% if e.user != current_user %>
    <h5 class="text-left <%= @class %>" id="<%= @class %>" style="font-size: 30px;" data-id="<%= e.user.id %>"><%= link_to "@#{e.user.name}", user_path(e.user_id) %></h5>
  <% else %>
    <h5 class="text-left <%= @class %>" id="<%= @class %>" data-id="<%= e.user.id %>"></h5>
  <% end %>
<% end %>

<div id="direct_messages" data-room_id="<%= @room.id %>">
  <%= render @direct_messages %>
</div>

<form>
  <div class="form-group">
    <label for="chat-input" style="color: white;">新しいメッセージを作成</label>
    <div class="input-group mb-3">
      <input type="text" id="chat-input" data-behavior="room_speaker" class="form-control">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="submit"><i class="fas fa-paper-plane"></i></button>
      </div>
    </div>
  </div>
</form>

<script>
  var element = document.getElementById('target');
  var rect = element.getBoundingClientRect();
  var position = rect.top;
  setTimeout( function() {
    scrollTo(0, position);
  }, 1000);
</script>

app/views/shifts/edit.html.erb
<h1>スケジュールの編集</h1>

<div class="card">
  <div class="card-body">
    <%= form_with model: @shift, url: shift_path do |form| %>
      <div class="form-group">
        <%= form.label :start_time %>
        <%= form.datetime_local_field :start_time, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :end_time %>
        <%= form.datetime_local_field :end_time, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :user_id %>
        <%= form.collection_select :user_id, User.all, :id, :name, { class: "form-control" } %>
      </div>

      <div class="form-group">
        <%= form.submit "更新する", class: "btn btn-primary" %>
        <%= link_to "戻る", shift_path(@shift), class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shifts/index.html.erb
<h1>スケジュール一覧</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>日時</th>
      <th>担当者</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.start_time.strftime('%Y/%m/%d %H:%M') %> 〜 <%= shift.end_time.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= shift.user.name %></td>
        <td>
          <%= link_to "<i class='fas fa-info'></i>".html_safe, shift_path(shift), class: "btn btn-info btn-sm mr-1", title: "詳細" %>
          <%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_shift_path(shift), class: "btn btn-primary btn-sm mr-1", title: "編集" %>
          <%= link_to "<i class='fas fa-trash'></i>".html_safe, shift_path(shift), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm", title: "削除" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "<i class='fas fa-plus'></i> 新規作成".html_safe, new_shift_path, class: "btn btn-success mb-3", title: "新規作成" %>

app/views/shifts/new.html.erb
<h1 class="mb-4">スケジュールの新規作成</h1>

<%= form_with model: @shift, url: shifts_path, class: "row g-3" do |form| %>
  <div class="col-md-6">
    <%= form.label :start_time, class: "form-label" %>
    <%= form.datetime_local_field :start_time, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :end_time, class: "form-label" %>
    <%= form.datetime_local_field :end_time, class: "form-control" %>
  </div>

  <div class="col-md-12">
    <%= form.label :user_id, "担当者", class: "form-label" %>
    <%= form.collection_select :user_id, User.all, :id, :name, { prompt: "選択してください" }, class: "form-select" %>
  </div>

  <div class="col-12 mt-4">
    <%= form.submit "作成する", class: "btn btn-primary" %>
    <%= link_to "戻る", shifts_path, class: "btn btn-secondary ms-2" %>
  </div>
<% end %>

app/views/shifts/show.html.erb
<h1 class="text-center mb-4">スケジュール詳細</h1>

<div class="card">
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>日時</th>
          <th>担当者</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @shift.start_time.strftime('%Y/%m/%d %H:%M') %> 〜 <%= @shift.end_time.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= @shift.user.name %></td>
          <td>
            <%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_shift_path(@shift.id), class: "btn btn-secondary btn-sm" %>
            <%= link_to "<i class='fas fa-trash'></i>".html_safe, shift_path(@shift.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<%= form_with model:@user, url:user_path(@user.id), local:true, class:'form' do |f| %>
  <div class="form-group">
    <%= f.label :name, class:'control-label' %>
    <div class="input-group">
      <%= f.text_field :name, class:'form-control' %>
          <span class="input-group-text"><i class="fas fa-user"></i></span>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit "Update User", class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>出席数:</h1>
<% @users.each do |user| %>
  <div class="d-flex justify-content-between align-items-center mb-3">
    <%= link_to user_path(user.id), class: "text-dark text-decoration-none" do %>
      <span><%= user.name %></span>
    <% end %>
    <span class="badge badge-primary"><%= user.attendances.count %>件</span>
  </div>
<% end %>

app/views/users/show.html.erb
<p>プロフィール画面</p>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @user.name %></h5>
    <p class="card-text"><%= @user.attendances.count %>件</p>
  </div>
</div>

<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>名前</th>
      <th>出席時刻</th>
      <th>退席時刻</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.user.name %></td>
        <td><%= attendance.clock_in_at.to_s(:datetime_jp) %></td>
        <td><%= attendance.clock_out_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "編集", edit_user_path(@user.id), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <% unless @user.id == current_user.id %>
    <!-- 既にroomが存在していれば既存のroomへ -->
    <% if @isRoom == true %>
      <!-- メールアイコンでroomに飛べるようにする -->
      <div class="mt-4">
        <%= link_to room_path(@roomId), class: "btn btn-success" do %>
          <i class="fas fa-envelope"></i> メッセージを送る
        <% end %>
      </div>
    <% else %>
      <!-- roomが存在していなければroomを作成する  -->
      <%= form_for @room, url: rooms_path do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, :value=> @user.id %>
        <% end %>
        <div class="mt-4">
          <%= f.submit "メッセージを送る", class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>